DROP TABLE Buying_VIP_Ticket CASCADE ;
DROP TABLE Buying_Regular_Ticket CASCADE ;
DROP TABLE Regular_Seat CASCADE ;
DROP TABLE VIP_Seat CASCADE ;
DROP TABLE Seat CASCADE ;
DROP TABLE Flown_by CASCADE ;
DROP TABLE Flight CASCADE ;
DROP TABLE Airplane CASCADE ;
DROP TABLE Pilot CASCADE ;
DROP TABLE Regular_Client CASCADE ;
DROP TABLE VIP_Client CASCADE ;
DROP TABLE Client CASCADE ;
DROP TABLE Person CASCADE ;


